# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

"""
Build-and-run helper for the cocotb testbenches (sim/runners/sim_runner.py).

Single source of truth for which HDL files make up an RTL or gate-level (GLS)
simulation, where each build and run lives, and what environment the simulator
needs. Used by sim/runners/test_sim.py; replaces the old sim/Makefile.

Layout (all under build/sim/):
    <sim>[-gls]/<toplevel>/                  one compiled simulation per toplevel,
                                             shared by every test of that toplevel
    <sim>[-gls]/<toplevel>/run_<module>/     cwd, results and logs of one test module

Each test module runs in its own directory with its own results file, so any
two tests (even of the same toplevel) can run concurrently; the compile step is
serialized per build directory with a file lock.
"""

import fcntl
import os
import subprocess
import sys
from contextlib import contextmanager
from pathlib import Path

from cocotb_tools.runner import get_runner

SIM_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = SIM_DIR.parent
BUILD_DIR = REPO_ROOT / "build"
VERYL_OUT_DIR = BUILD_DIR / "veryl"
SYNTH_DIR = BUILD_DIR / "synth"
FIRMWARE_BUILD_DIR = BUILD_DIR / "firmware"
SIM_BUILD_DIR = BUILD_DIR / "sim"

# Directories holding cocotb test modules (imported by name inside the simulator)
TEST_MODULE_DIRS = [SIM_DIR / "unit", SIM_DIR / "integration"]

_CPU = ["rv32i_pkg", "rv32i_alu", "rv32i_decode", "rv32i_regfile", "rv32i_csrs", "hack_translator",
        "auto_mode_detector", "unified_cpu"]  # fmt: skip
_UART = ["clk_timer", "shift_registers", "fifo_sync", "uart_tx", "uart_rx", "uart_controller"]
_SOC = ["timer_core", "sdcard_spi", "gpio_controller", "soc_ram", "soc_top"]

# Generated by `veryl build --out-dir build/veryl` (package first), plus the SoC clock wrapper
RTL_SOURCES = (
    [VERYL_OUT_DIR / "soc" / "cpu" / f"{m}.sv" for m in _CPU]
    + [VERYL_OUT_DIR / "soc" / "uart" / f"{m}.sv" for m in _UART]
    + [VERYL_OUT_DIR / "soc" / f"{m}.sv" for m in _SOC]
    + [SIM_DIR / "tb_soc_top.sv"]
)

# soc_ram's $readmemh() calls use bare file names, resolved against the simulator's cwd
FIRMWARE_HEX = ["firmware.hex", "firmware_d0.hex", "firmware_d1.hex", "firmware_d2.hex", "firmware_d3.hex"]


def gls_sources(toplevel: str) -> list[Path]:
    """Gowin cell models + the yosys netlist for toplevel (+ the clock wrapper)."""
    netlist = "soc_syn.v" if toplevel in ("soc_top", "tb_soc_top") else f"{toplevel}_syn.v"
    return [SIM_DIR / "gowin_cells_sim.v", SYNTH_DIR / netlist, SIM_DIR / "tb_soc_top.sv"]


def _libs_to_preload() -> str:
    """oss-cad-suite's vvp runs under its own ld.so/library path, where the uv-built
    libpython can't find librt/libutil ("librt.so.1: cannot open shared object file")."""
    libs = []
    for name in ("librt.so.1", "libutil.so.1"):
        try:
            path = subprocess.run(["gcc", f"-print-file-name={name}"], capture_output=True, text=True).stdout.strip()
        except FileNotFoundError:
            continue
        if os.path.isabs(path) and os.path.exists(path):
            libs.append(path)
    return " ".join(libs)


@contextmanager
def _exclusive(lock_path: Path):
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with open(lock_path, "w") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def _stage_firmware(test_dir: Path):
    for name in FIRMWARE_HEX:
        src = FIRMWARE_BUILD_DIR / name
        dst = test_dir / name
        if src.exists() and not dst.exists():
            dst.symlink_to(src)


def run(toplevel: str, module: str, *, gls: bool = False, sim: str | None = None, testcase: str | None = None):
    """Compile (if outdated) and run one cocotb test module against toplevel.

    sim defaults to $SIM, else "icarus". Raises on missing sources; under pytest,
    a failing cocotb test fails the calling pytest test.
    """
    sim = sim or os.environ.get("SIM", "icarus")
    variant = f"{sim}-gls" if gls else sim
    build_dir = SIM_BUILD_DIR / variant / toplevel
    test_dir = build_dir / f"run_{module}"

    sources = gls_sources(toplevel) if gls else RTL_SOURCES
    missing = [str(s.relative_to(REPO_ROOT)) for s in sources if not s.exists()]
    if missing:
        hint = "make synth-top / make synth-units" if gls else "make veryl"
        raise FileNotFoundError(f"Missing HDL sources (run `{hint}` first): {', '.join(missing)}")

    for d in TEST_MODULE_DIRS:
        if str(d) not in sys.path:
            sys.path.insert(0, str(d))

    runner = get_runner(sim)
    with _exclusive(build_dir.with_name(f"{toplevel}.lock")):
        runner.build(
            sources=sources,
            hdl_toplevel=toplevel,
            build_dir=build_dir,
            build_args=["-g2012"],
            timescale=("1ns", "1ps"),
        )

    test_dir.mkdir(parents=True, exist_ok=True)
    _stage_firmware(test_dir)
    extra_env = {}
    preload = _libs_to_preload()
    if preload and "LD_PRELOAD" not in os.environ:
        extra_env["LD_PRELOAD"] = preload
    runner.test(
        test_module=module,
        hdl_toplevel=toplevel,
        build_dir=build_dir,
        test_dir=test_dir,
        testcase=testcase,
        extra_env=extra_env,
    )
