# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

"""
Build-and-run helper for the cocotb testbenches (sim/runners/sim_runner.py).

Single source of truth for which HDL files make up an RTL or gate-level (GLS)
simulation, where each build and run lives, and what environment the simulator
needs. Used by sim/runners/test_sim.py; replaces the old sim/Makefile.

Layout (all under build/sim/):
    <sim>[-gls]/<toplevel>/                  one compiled simulation per toplevel,
                                             shared by every test of that toplevel
    <sim>[-gls]/<toplevel>/run_<module>/     cwd, results and logs of one test module
    verilator-cov/...                        same, instrumented for COVERAGE=1

Each test module runs in its own directory with its own results file, so any
two tests (even of the same toplevel) can run concurrently; the compile step is
serialized per build directory with a file lock.
"""

import fcntl
import os
import subprocess
import sys
from contextlib import contextmanager
from pathlib import Path

from cocotb_tools.runner import Verilator, VerilatorControlFile, get_runner

SIM_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = SIM_DIR.parent
BUILD_DIR = REPO_ROOT / "build"
VERYL_OUT_DIR = BUILD_DIR / "veryl"
SYNTH_DIR = BUILD_DIR / "synth"
FIRMWARE_BUILD_DIR = BUILD_DIR / "firmware"
SIM_BUILD_DIR = BUILD_DIR / "sim"

# Directories holding cocotb test modules (imported by name inside the simulator)
TEST_MODULE_DIRS = [SIM_DIR / "unit", SIM_DIR / "integration"]

_CPU = ["rv32i_pkg", "rv32i_alu", "rv32i_decode", "rv32i_regfile", "rv32i_csrs", "hack_translator",
        "auto_mode_detector", "unified_cpu"]  # fmt: skip
_UART = ["clk_timer", "shift_registers", "fifo_sync", "uart_tx", "uart_rx", "uart_controller"]
_SOC = ["timer_core", "sdcard_spi", "gpio_controller", "soc_ram", "soc_top"]

# Generated by `veryl build --out-dir build/veryl` (package first)
RTL_SOURCES = (
    [VERYL_OUT_DIR / "soc" / "cpu" / f"{m}.sv" for m in _CPU]
    + [VERYL_OUT_DIR / "soc" / "uart" / f"{m}.sv" for m in _UART]
    + [VERYL_OUT_DIR / "soc" / f"{m}.sv" for m in _SOC]
)
# SoC clock wrapper (sim/tb_soc_top.sv), added only when it is the toplevel
TB_SOC_TOP = SIM_DIR / "tb_soc_top.sv"

# Per-simulator compile flags
BUILD_ARGS = {
    "icarus": ["-g2012"],
    # --timing: tb_soc_top.sv generates the clock with `#` delays.
    # Lint warnings on Veryl-generated code are not actionable here (Veryl's own
    # checks run in `make check`), so keep them from failing the build.
    "verilator": ["--timing", "-Wno-fatal", "-Wno-lint", "-Wno-style"],
}

# COVERAGE=1 (Verilator RTL only, see `make coverage`): line + toggle coverage.
# Instrumented builds live in their own build/sim/verilator-cov/ tree; each test
# writes coverage.dat into its run directory when the simulation exits.
COVERAGE_ARGS = ["--coverage-line", "--coverage-toggle"]

# Internal (non-toplevel) signals the RTL SoC tests read or write, as (module, var).
# Under Verilator only these plus the toplevel's own signals are made VPI-visible;
# see _VerilatorWithSelectivePublic. Add to this list when a test reaches deeper.
SOC_RTL_PUBLIC = [
    ("soc_top", "*"),  # por_counter, active_mode, clk, ...
    ("unified_cpu", "pc_out"),  # dut.cpu_inst.pc_out
    ("soc_ram", "i_mem"),  # dut.ram_inst.i_mem[] (firmware preload)
]

# soc_ram's $readmemh() calls use bare file names, resolved against the simulator's cwd
FIRMWARE_HEX = ["firmware.hex", "firmware_d0.hex", "firmware_d1.hex", "firmware_d2.hex", "firmware_d3.hex"]


def sources_for(toplevel: str, gls: bool) -> list[Path]:
    """RTL sources, or Gowin cell models + the yosys netlist for toplevel (GLS)."""
    if gls:
        netlist = "soc_syn.v" if toplevel in ("soc_top", "tb_soc_top") else f"{toplevel}_syn.v"
        sources = [SIM_DIR / "gowin_cells_sim.v", SYNTH_DIR / netlist]
    else:
        sources = list(RTL_SOURCES)
    if toplevel == "tb_soc_top":
        sources.append(TB_SOC_TOP)
    return sources


class _VerilatorWithSelectivePublic(Verilator):
    """cocotb's Verilator runner, minus its blanket --public-flat-rw.

    --public-flat-rw makes every signal VPI-accessible, which blocks most of
    Verilator's optimizations: on the gate-level soc_top netlist it made
    simulation ~18x slower (test_soc_gls_fast: 139 s -> 7.8 s without it) and
    compiling ~5x slower. Visibility comes from a generated .vlt instead.
    """

    def _build_command(self):
        cmds = super()._build_command()
        cmds[0] = [arg for arg in cmds[0] if arg != "--public-flat-rw"]
        return cmds


def _public_vlt(build_dir: Path, toplevel: str, gls: bool) -> VerilatorControlFile:
    """Verilator control file exposing the toplevel (+ SOC_RTL_PUBLIC for RTL SoC builds)."""
    entries = [(toplevel, "*")]
    if not gls and toplevel in ("soc_top", "tb_soc_top"):
        entries += SOC_RTL_PUBLIC
    lines = ["`verilator_config"] + [f'public_flat_rw -module "{m}" -var "{v}"' for m, v in entries]
    path = build_dir / "public.vlt"
    text = "\n".join(lines) + "\n"
    if not path.exists() or path.read_text() != text:
        path.write_text(text)
    return VerilatorControlFile(path)


def _libs_to_preload() -> str:
    """oss-cad-suite's vvp runs under its own ld.so/library path, where the uv-built
    libpython can't find librt/libutil ("librt.so.1: cannot open shared object file")."""
    libs = []
    for name in ("librt.so.1", "libutil.so.1"):
        try:
            path = subprocess.run(["gcc", f"-print-file-name={name}"], capture_output=True, text=True).stdout.strip()
        except FileNotFoundError:
            continue
        if os.path.isabs(path) and os.path.exists(path):
            libs.append(path)
    return " ".join(libs)


@contextmanager
def _exclusive(lock_path: Path):
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with open(lock_path, "w") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def _stage_firmware(test_dir: Path):
    for name in FIRMWARE_HEX:
        src = FIRMWARE_BUILD_DIR / name
        dst = test_dir / name
        if src.exists() and not dst.exists():
            dst.symlink_to(src)


def run(toplevel: str, module: str, *, gls: bool = False, sim: str | None = None, testcase: str | None = None):
    """Compile (if outdated) and run one cocotb test module against toplevel.

    sim defaults to $SIM, else "icarus". Raises on missing sources; under pytest,
    a failing cocotb test fails the calling pytest test.
    """
    sim = sim or os.environ.get("SIM", "icarus")
    coverage = os.environ.get("COVERAGE", "") not in ("", "0")
    if coverage and (sim != "verilator" or gls):
        raise ValueError("COVERAGE=1 needs SIM=verilator and an RTL (non-GLS) build")
    variant = f"{sim}-gls" if gls else sim
    if coverage:
        variant += "-cov"
    build_dir = SIM_BUILD_DIR / variant / toplevel
    test_dir = build_dir / f"run_{module}"

    sources = sources_for(toplevel, gls)
    paths = [Path(getattr(s, "value", s)) for s in sources]  # sources may be runner tags
    missing = [str(p.relative_to(REPO_ROOT)) for p in paths if not p.exists()]
    if missing:
        hint = "make synth-top / make synth-units" if gls else "make veryl"
        raise FileNotFoundError(f"Missing HDL sources (run `{hint}` first): {', '.join(missing)}")

    for d in TEST_MODULE_DIRS:
        if str(d) not in sys.path:
            sys.path.insert(0, str(d))

    runner = _VerilatorWithSelectivePublic() if sim == "verilator" else get_runner(sim)
    build_args = BUILD_ARGS[sim] + (COVERAGE_ARGS if coverage else [])
    with _exclusive(build_dir.with_name(f"{toplevel}.lock")):
        if sim == "verilator":
            # The runner infers the HDL language from the *last* source, so the .vlt goes first
            build_dir.mkdir(parents=True, exist_ok=True)
            sources = [_public_vlt(build_dir, toplevel, gls)] + sources
        # cocotb only rebuilds when a source is newer than the binary; also rebuild
        # when the compile flags changed, or a flag edit would silently not apply.
        stamp = build_dir / ".build_args"
        flags = "\n".join(build_args)
        flags_changed = not stamp.exists() or stamp.read_text() != flags
        runner.build(
            sources=sources,
            hdl_toplevel=toplevel,
            build_dir=build_dir,
            build_args=build_args,
            timescale=("1ns", "1ps"),
            always=flags_changed,
        )
        stamp.write_text(flags)

    test_dir.mkdir(parents=True, exist_ok=True)
    _stage_firmware(test_dir)
    if coverage:
        (test_dir / "coverage.dat").unlink(missing_ok=True)  # never merge a stale run
    extra_env = {}
    preload = _libs_to_preload()
    if preload and "LD_PRELOAD" not in os.environ:
        extra_env["LD_PRELOAD"] = preload
    runner.test(
        test_module=module,
        hdl_toplevel=toplevel,
        build_dir=build_dir,
        test_dir=test_dir,
        testcase=testcase,
        extra_env=extra_env,
    )
