# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

"""
SD card transcripts (sim/sd_transcripts/*.txt): byte-level MOSI/CS -> MISO exchanges
of firmware-like host sequences, recorded from the RTL tests' card
(sim/integration/sdcard_protocol.py). This test re-records every scenario and
compares with the committed file; emu/crates/vux9k_emu/tests/sd_transcripts.rs
replays the same files through the emulator's card. Together they keep the two
cards identical at byte level.

After an intended change of the Python card: SD_TRANSCRIPTS_UPDATE=1 pytest this
file, review the diff, and make the Rust card match.

File format, one record per line ('#' comments):
  card sdhc=0|1 strict=0|1 [mute=N,N] [bad=LBA,LBA] [never_ready] [read_error] [write_reject]
  sector LBA HEX             preloaded sector
  cs 0|1                     CS change (1 = selected)
  x 0|1 MOSI-HEX MISO-HEX    bytes clocked with CS at that level, and the answers
  expect-sector LBA HEX
  expect-commands CMD:ARG,...
  expect-violations N
  expect-idle-clocks N
"""

import os
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO_ROOT, "sim", "integration"))
from sdcard_protocol import SECTOR, SdCardProtocol  # noqa: E402

DIR = os.path.join(REPO_ROOT, "sim", "sd_transcripts")


class Recorder:
    """Host side, as the firmware drives the SPI master (transfer/set_cs/send_cmd)."""

    def __init__(self, name, **card):
        self.card = SdCardProtocol(**card)
        opts = [f"sdhc={int(self.card.sdhc)}", f"strict={int(self.card.strict)}"]
        if card.get("mute_cmds"):
            opts.append("mute=" + ",".join(str(c) for c in card["mute_cmds"]))
        if card.get("bad_sectors"):
            opts.append("bad=" + ",".join(str(c) for c in card["bad_sectors"]))
        opts += [f for f in ("never_ready", "read_error", "write_reject") if card.get(f)]
        self.lines = [f"# {name}: generated by sim/emu/test_sd_transcripts.py", "card " + " ".join(opts)]
        self.selected = False
        self._run = None  # [sel, mosi bytearray, miso bytearray]

    def _flush(self):
        if self._run:
            sel, mosi, miso = self._run
            self.lines.append(f"x {int(sel)} {mosi.hex()} {miso.hex()}")
            self._run = None

    def sector(self, lba, data):
        self.card.set_sector(lba, data)
        self.lines.append(f"sector {lba} {self.card.get_sector(lba).hex()}")

    def cs(self, selected):
        self._flush()
        if selected != self.selected:
            self.selected = selected
            self.card.set_cs(selected)
            self.lines.append(f"cs {int(selected)}")

    def xfer(self, b):
        if self._run is None or self._run[0] != self.selected:
            self._flush()
            self._run = [self.selected, bytearray(), bytearray()]
        m = self.card.exchange(b, self.selected)
        self._run[1].append(b)
        self._run[2].append(m)
        return m

    def cmd(self, cmd, arg, crc=0x95):
        self.cs(True)
        for b in bytes([0x40 | cmd]) + arg.to_bytes(4, "big") + bytes([crc]):
            self.xfer(b)
        for _ in range(200):
            r = self.xfer(0xFF)
            if r != 0xFF:
                return r
        return 0xFF

    def deselect(self):
        self.cs(False)
        self.xfer(0xFF)

    def read(self, n):
        return bytes(self.xfer(0xFF) for _ in range(n))

    def init(self):
        """The Boot Manager's SdCard::init()."""
        self.deselect()
        for _ in range(16):
            self.xfer(0xFF)
        self.cmd(0, 0)
        self.deselect()
        if self.cmd(8, 0x1AA, 0x87) == 0x01:
            self.read(4)
        self.deselect()
        for _ in range(3):
            r55 = self.cmd(55, 0, 0x65)
            self.deselect()
            r = self.cmd(41, 0x4000_0000, 0x77) if r55 <= 1 else self.cmd(1, 0x4000_0000)
            self.deselect()
            if r == 0:
                break
        if self.cmd(58, 0, 0xFD) == 0:
            self.read(4)
        self.deselect()
        self.cmd(16, 512)
        self.deselect()

    def read_block(self, addr):
        """SdCard::read_block (token wait, 512 bytes, CRC)."""
        if self.cmd(17, addr) != 0:
            self.deselect()
            return None
        for _ in range(8):
            if self.xfer(0xFF) == 0xFE:
                break
        else:
            self.deselect()
            return None
        data = self.read(SECTOR)
        self.read(2)
        self.deselect()
        return data

    def write_block(self, addr, data):
        """SdCard::write_block up to the busy wait."""
        if self.cmd(24, addr) != 0:
            self.deselect()
            return None
        self.xfer(0xFF)
        self.xfer(0xFE)
        for b in data:
            self.xfer(b)
        self.read(2)
        resp = self.xfer(0xFF)
        for _ in range(8):
            if self.xfer(0xFF) == 0xFF:
                break
        self.deselect()
        return resp

    def finish(self, expect_sectors=()):
        self._flush()
        c = self.card
        for lba in expect_sectors:
            self.lines.append(f"expect-sector {lba} {c.get_sector(lba).hex()}")
        self.lines.append("expect-commands " + ",".join(f"{cmd}:{arg:x}" for cmd, arg in c.commands))
        self.lines.append(f"expect-violations {len(c.violations)}")
        self.lines.append(f"expect-idle-clocks {c.idle_clocks}")
        return "\n".join(self.lines) + "\n"


def pattern(seed):
    return bytes((seed * 7 + i * 13) & 0xFF for i in range(SECTOR))


def sdhc_read_write():
    h = Recorder("sdhc_read_write")
    h.sector(1, pattern(1))
    h.init()
    h.read_block(1)
    h.write_block(3, pattern(3))
    h.read_block(3)
    h.read_block(0x20 << 9)  # forgiving: a byte address >= 0x10000
    h.cmd(24, 7)
    h.deselect()  # CS rises while the card waits for the data token
    h.cmd(8, 0x1AA)  # answer not read to the end...
    h.deselect()
    h.cmd(55, 0)  # ...so this command is lost
    h.deselect()
    h.cs(True)
    h.xfer(0x51)  # partial command dropped by CS
    h.xfer(0)
    h.deselect()
    h.cmd(13, 0)  # unknown: no answer
    h.deselect()
    return h.finish(expect_sectors=[3, 7])


def sdsc_strict():
    h = Recorder("sdsc_strict", sdhc=False, strict=True)
    h.sector(2, pattern(2))
    h.cs(True)  # no power-up clocks with CS high
    h.cmd(0, 0)
    h.deselect()
    h.init()
    h.read_block(2 << 9)
    h.read_block(2)  # a block address: violation
    h.write_block(5 << 9, pattern(5))
    return h.finish(expect_sectors=[5])


def faults():
    h = Recorder("faults", mute_cmds=[8], never_ready=True, read_error=True, write_reject=True)
    h.init()
    h.read_block(0)
    h.write_block(4, pattern(4))
    return h.finish(expect_sectors=[4])


def bad_sector():
    h = Recorder("bad_sector", bad_sectors=[5])
    for lba in (4, 5, 6):
        h.sector(lba, pattern(lba))
    h.init()
    for lba in (4, 5, 6):
        h.read_block(lba)
    return h.finish()


def mute_cmd55():
    """CMD55 unanswered: the Boot Manager's CMD1 fallback"""
    h = Recorder("mute_cmd55", mute_cmds=[55])
    h.init()
    return h.finish()


def mute_cmd0():
    h = Recorder("mute_cmd0", mute_cmds=[0])
    h.init()
    return h.finish()


SCENARIOS = {f.__name__: f for f in (sdhc_read_write, sdsc_strict, faults, bad_sector, mute_cmd55, mute_cmd0)}


@pytest.mark.parametrize("name", SCENARIOS)
def test_transcript(name):
    text = SCENARIOS[name]()
    path = os.path.join(DIR, f"{name}.txt")
    if os.environ.get("SD_TRANSCRIPTS_UPDATE"):
        with open(path, "w") as f:
            f.write(text)
    assert os.path.exists(path), f"{path} missing; run with SD_TRANSCRIPTS_UPDATE=1"
    with open(path) as f:
        assert f.read() == text, f"{name}: the Python SD card no longer matches {path}"
