# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tbootstrap/link.x",
]
