#!/usr/bin/env python3
# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

"""
Static Timing Analysis (STA) Report Generator for nextpnr.
Parses JSON timing reports generated by nextpnr and formats an intuitive summary.
"""

import json
import sys
import os
import argparse


def format_delay(val_ns):
    return f"{val_ns:.2f} ns"


def analyze_sta(report_path, target_freq_mhz=27.0):
    if not os.path.exists(report_path):
        print(f"Error: Timing report file '{report_path}' not found.", file=sys.stderr)
        return False

    with open(report_path, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
        except Exception as e:
            print(f"Error parsing JSON file '{report_path}': {e}", file=sys.stderr)
            return False

    critical_paths = data.get("critical_paths", [])
    if not critical_paths:
        print("No critical path data found in timing report.")
        return True

    target_period_ns = 1000.0 / target_freq_mhz

    print("=" * 80)
    print("           VUX9K STATIC TIMING ANALYSIS (STA) REPORT (nextpnr)")
    print("=" * 80)
    print(f"Target Clock Frequency : {target_freq_mhz:.2f} MHz (Period: {target_period_ns:.2f} ns)")
    print(f"Report Source File     : {report_path}")
    print("-" * 80)

    overall_pass = True

    for i, cp in enumerate(critical_paths, 1):
        clock_from = cp.get("from", "Unknown")
        clock_to = cp.get("to", "Unknown")
        path_elements = cp.get("path", [])

        total_delay = sum(elem.get("delay", 0.0) for elem in path_elements)
        logic_delay = sum(
            elem.get("delay", 0.0)
            for elem in path_elements
            if elem.get("type") in ("logic", "clk-to-q", "setup")
        )
        routing_delay = sum(
            elem.get("delay", 0.0)
            for elem in path_elements
            if elem.get("type") == "routing"
        )

        fmax_mhz = 1000.0 / total_delay if total_delay > 0 else 0.0
        slack_ns = target_period_ns - total_delay

        logic_pct = (logic_delay / total_delay * 100.0) if total_delay > 0 else 0.0
        routing_pct = (routing_delay / total_delay * 100.0) if total_delay > 0 else 0.0

        status = "PASS" if slack_ns >= 0 else "FAIL"
        if status == "FAIL":
            overall_pass = False

        print(f"\n[Clock Domain #{i}] {clock_from} -> {clock_to}")
        print(f"  Status              : [{status}] (Slack: {slack_ns:+.2f} ns)")
        print(f"  Max Frequency (Fmax): {fmax_mhz:.2f} MHz")
        print(f"  Total Data Delay    : {total_delay:.2f} ns")
        print(f"    - Logic Delay     : {logic_delay:.2f} ns ({logic_pct:.1f}%)")
        print(f"    - Routing Delay   : {routing_delay:.2f} ns ({routing_pct:.1f}%)")

        sorted_elements = sorted(
            [e for e in path_elements if e.get("delay", 0.0) > 0],
            key=lambda x: x.get("delay", 0.0),
            reverse=True,
        )

        print("\n  Top Critical Path Delay Segments:")
        print(f"  {'Type':<10} {'Delay':<10} {'Location':<12} {'Cell / Net Name'}")
        print(f"  {'-'*8}   {'-'*8}   {'-'*10}   {'-'*45}")

        for elem in sorted_elements[:10]:
            elem_type = elem.get("type", "unknown")
            delay_str = format_delay(elem.get("delay", 0.0))
            loc = elem.get("from", {}).get("loc", ["-", "-"])
            loc_str = f"({loc[0]},{loc[1]})" if isinstance(loc, list) and len(loc) == 2 else "-"

            name = ""
            if elem_type == "routing":
                name = f"Net: {elem.get('net', '')}"
            else:
                from_cell = elem.get("from", {}).get("cell", "")
                from_port = elem.get("from", {}).get("port", "")
                to_port = elem.get("to", {}).get("port", "")
                name = f"Cell: {from_cell} ({from_port}->{to_port})"

            if len(name) > 48:
                name = name[:45] + "..."

            print(f"  {elem_type:<10} {delay_str:<10} {loc_str:<12} {name}")

    print("\n" + "=" * 80)
    if overall_pass:
        print("  TIMING SUMMARY: ALL CLOCK DOMAINS MET TIMING CONSTRAINTS! [PASS]")
    else:
        print("  TIMING SUMMARY: TIMING CONSTRAINTS FAILED OR CRITICAL SLACK DETECTED! [FAIL]")
    print("=" * 80 + "\n")

    return overall_pass


def main():
    parser = argparse.ArgumentParser(description="Format nextpnr STA JSON report.")
    parser.add_argument("report", nargs="?", default="soc_sta.json", help="Path to nextpnr JSON report")
    parser.add_argument("--freq", type=float, default=27.0, help="Target clock frequency in MHz (default: 27.0)")
    parser.add_argument("--strict", action="store_true", help="Exit with non-zero code on timing violation")

    args = parser.parse_args()
    passed = analyze_sta(args.report, target_freq_mhz=args.freq)

    if args.strict and not passed:
        sys.exit(1)


if __name__ == "__main__":
    main()
